### ISSUE TITLE
Add support for Jobs Schedule operations

### ISSUE THREAD

**Issue by wasdal** [plexilar/kladama-api-python#25]
Add operations in the API for browsing, checking and cleaning the Jobs Schedule.

kladama.com/schedule {?user=<USER>}

kladama.com/schedule/clear{?user=<USER>&subsc=<CODE>}

kladama.com/schedule/check?user=<USER>{&subsc=<CODE>}

**Comment by hdkrus** [comment]
This issue is been addressed in #22
